### ISSUE TITLE
Composer Vendor Directory

### ISSUE THREAD

**Issue by neerajsohal** [razorpay/razorpay-php#1]
Currently, Vendor directory is excluded from .gitignore. Vendor directories should not be included in the source code commits.

**Comment by harshilmathur** [comment]
Hi, You are right, we are fully aware of that, but some customers have trouble understanding/using composer, hence this has been done as a temporary measure. Will keep this issue open until fixed. Thanks!

**Comment by neerajsohal** [comment]
In that case, I think the best way should be to create two branches or a separate branch for people who are not comfortable with the composer. There are other ways too. Can't remember them right now. will add to the thread.

PS: Not being rude :)

**Comment by captn3m0** [comment]
I want to setup a simple deploy process (in travis perhaps) where each new tag automatically creates a "downloadable" release in github releases section, for the non-composer folks.

**Comment by neerajsohal** [comment]
When you tag your code, it automatically releases it as a downloadable zip file if I am not wrong. You can checkout http://github.com/atomforthings/protocol-lib-php/tags. Something I am currently working on.
