### ISSUE TITLE
Unable to fetch transfers

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [razorpay/razorpay-php#103]
My transfer is successful, but when I am fetching it, I am getting an empty result,

```
$apiKey = env('RAZORPAY_API_KEY');
        $apiSecret = env('RAZORPAY_SECRET_KEY');
        $api = new Api($apiKey, $apiSecret);
        $paymentId = 'pay_CdJPa3B6n1o8ag';

        $transferDetails = [
             [
                'account' => 'acc_####',
                'amount' => 100, 
                'currency' => 'INR',
                'notes' => [
                    'name' => 'PQR pvt Ltd'
                ]
            ],
            [
                'account' => 'acc_####',
                'amount' => 100, 
                'currency' => 'INR',
                'notes' => [
                    'name' => 'Abc Pvt ltd'
                ]
            ]
        ];
    
        $transfers  = $api->payment->fetch($paymentId)->transfer(['transfers' => $transferDetails]); // Create transfer

    //    $transfers = $api->transfer->all();  even if I will try to fetch all the transfer, I am getting empty.

        return response()->json(
           [ 'transfers' => $transfers]
        );
```
**Note:** In report, I can see transactions are successful.

Any suggestion?

**Comment by jitendra-1217** [comment]
Hi @PrafullaKumarSahu .

Apologies for the delay in responding here. The call to transfer() returns all the created transfer details and you should be able to use it instead of making another call immediately after.

<details>
<summary>Sample json response from POST /payments/<id>/transfers call</summary>

Above php code call will return the equivalent php array.

```json
{
    "entity":"collection",
    "count":2,
    "items":[
        {
            "id":"trf_9A33XWu170gXBC",
            "entity":"transfer",
            "source":"pay_AlSXPEsTyXyxYx",
            "recipient":"acc_BYYYYJRfs1234S",
            "amount":10000,
            "currency":"INR",
            "amount_reversed":0,
            "on_hold":false,
            "notes":{
                "roll_no":"IEC2011025",
                "name":"Gaurav Kumar"
            },
            "linked_account_notes":[
                "roll_no"
            ],
            "tax":16,
            "fees":4,
            "created_at":1482996461
        },
        {
            "id":"trf_9A33XWu170gYYY",
            "entity":"transfer",
            "source":"pay_AlSXPEsTyXyxYx",
            "recipient":"acc_BYYYYJRfs1234S",
            "amount":10000,
            "currency":"INR",
            "amount_reversed":0,
            "on_hold":false,
            "notes":{
                "roll_no":"IEC2011026",
                "name":"Saurav Kumar"
            },
            "tax":16,
            "fees":4,
            "created_at":1482996461
        }
    ]
}
```

</details>

Also if you need to get details of a particular transfer(by id) you may use `$api->transfer->fetch($id)` call. Please refer [api doc](https://razorpay.com/docs/route/api/#create-transfers-from-payments) for details.

**Comment by jitendra-1217** [comment]
Please feel free to re-open the issue if it doesn't solve your problem.

**Comment by PrafullaKumarSahu** [comment]
@jitendra-1217  I am getting empty response for `$transfers  = $api->payment->fetch($paymentId)->transfer(['transfers' => $transferDetails]); // Create transfer` , am I doing anything wrong?

**Comment by jitendra-1217** [comment]
// $transfers = $api->payment->fetch($paymentId)->transfer(['transfers' => $transferDetails]); // Create transfer
No. You shouldn't get empty response on this call. Please check if you are getting non-200 response in which case also the response would have error details and not empty. Share payment id or some other input reference so we can check at our end.

**Comment by PrafullaKumarSahu** [comment]
@jitendra-1217 the payment Id, I have mentioned in the question, for that, I am getting an empty response.
