### ISSUE TITLE
Webhooks PHP code

### ISSUE THREAD

**Issue by pubspotapp** [razorpay/razorpay-php#104]
Hi,

I'm new to Payment integration and webhooks integration. Can anyone help with the Webhooks code in PHP. Below is a sample code i found...is this right?

use Razorpay\Api\Api;
$api = new Api("API_key", "API_secret");

$json=file_get_contents('php://input');
$webhookBody = json_decode($json);

$webhookSecret='Webhook_secret';
$webhookSignature = $api->header('X-Razorpay-Signature');
$api->utility->verifyWebhookSignature($webhookBody, $webhookSignature, $webhookSecret);

**Comment by captn3m0** [comment]
https://github.com/razorpay/razorpay-php/blob/a947f310b39707c50dcc2fbd542592b039cdd716/src/Utility.php#L38-L41

verifyWebhookSignature takes a string, please pass it $json instead of parsed JSON.

**Comment by jitendra-1217** [comment]
Please feel free to comment with if any issue still after above suggestion. For now assuming resolved and closing it.

**Comment by devqualwebs** [comment]
Hello,
I'm following the code which is using above. But facing this error `Call to undefined method Razorpay\Api\Api::header()`.
I checked this method in Razorpay/Api/Api.php file. But this method is not found. Can you please help me to fix this issue?

**Comment by jrkansagara** [comment]
Hello,
Can i get sample Webhook for Virtual Account Credited in PHP.
