### ISSUE TITLE
Fatal error: account, amount is/are not required and should not be sent

### ISSUE THREAD

**Issue by akadebnath** [razorpay/razorpay-php#106]
I tried to transfer a captured payment to linked account by calling the API:

`$trasnfer = $api->payment->fetch(<razorpay_payment_id>)->transfer(array('account'=><razorpay_linked_account_number>,'amount'=><amount_to_transfer>)); `

I am getting below error:

> PHP Fatal error:  Uncaught exception 'Razorpay\Api\Errors\BadRequestError' with message 'account, amount is/are not required and should not be sent' in /vendor/razorpay/razorpay/src/Request.php:123
> Stack trace:
> #0 /vendor/razorpay/razorpay/src/Request.php(90): Razorpay\Api\Request->processError(Array, 400, Object(Requests_Response))
> #1 /vendor/razorpay/razorpay/src/Request.php(44): Razorpay\Api\Request->checkErrors(Object(Requests_Response))
> #2 /vendor/razorpay/razorpay/src/Entity.php(79): Razorpay\Api\Request->request('POST', 'payments/pay_Cg...', Array)
> #3 /vendor/razorpay/razorpay/src/Payment.php(46): Razorpay\Api\Entity->request('POST', 'payments/pay_Cg...', Array)
> #4 /ajax_controller.php(848): Razorpay\Api\Payment->transfer(Array)
> #5 {main}
>   thrown in /vendor/razorpay/razorpay/src/Request.php on line 123

Can you please let me know what wrong I am doing here.

**Comment by jitendra-1217** [comment]
It seems the argument you are passing in transfer() call is incorrect. Please refer to example usage section of Transfers in https://github.com/razorpay/razorpay-php#usage doc for the correct argument structure.
