### ISSUE TITLE
While reloading verify page it will giving "true" condition always

### ISSUE THREAD

**Issue by prashantalphonic** [razorpay/razorpay-php#107]
After getting success on the payment page, it will go to the verify.php page. When we are reloading this page it will give "true" condition always but As per the correct manner, it will be killed automatically once after reloading the verify.php page.

Please help me out in this. We are waiting for this by so long.

Ticket no. 555062

**Comment by prashantalphonic** [comment]
require('razorpay-php/Razorpay.php');
use Razorpay\Api\Api;
use Razorpay\Api\Errors\SignatureVerificationError;

$success = true;
 $error = "Payment Failed";
if (empty($_POST['razorpay_payment_id']) === false)
{
    $api = new Api($keyId, $keySecret);

    try
    {
        // Please note that the razorpay order ID must
        // come from a trusted source (session here, but
        // could be database or something else)
        $attributes = array(
            'razorpay_order_id' => $_SESSION['razorpay_order_id'],
            'razorpay_payment_id' => $_POST['razorpay_payment_id'],
            'razorpay_signature' => $_POST['razorpay_signature']
        );

        $api->utility->verifyPaymentSignature($attributes);
    }
    catch(SignatureVerificationError $e)
    {
        $success = false;
        $error = 'Razorpay Error : ' . $e->getMessage();
    }
}

if ($success === true)
{
         // Always giving True(after getting relaod too)
}

**Comment by jitendra-1217** [comment]
Why should reload of page(with confirm data re submission) fail in the code posted above ^? Maybe you should unset the session's order id in first execution?

Request to give bit more details around integrated flow.

**Comment by captn3m0** [comment]
Stale issue, closing
