### ISSUE TITLE
no matches found: razorpay/razorpay:2.*

### ISSUE THREAD

**Issue by syamantak** [razorpay/razorpay-php#110]
When i run composer require razorpay/razorpay:2.*,  i am getting no matches found: razorpay/razorpay:2.*

Any idea ?

**Comment by captn3m0** [comment]
Can you try quoting the `*` in the command:

`composer require "razorpay/razorpay:2.*"`

I've just tested it, and it works. Please provide your composer+php version if it still doesn't work for you.

**Comment by TsingXu430** [comment]
I use this command: composer require "razorpay/razorpay:2.*"
it's also getting a error: no matches found
then I edit the composer.json :  "require": {
		"razorpay/razorpay": "2.*"
	}
it's work
