### ISSUE TITLE
Missing: subscription.authenticated webhook

### ISSUE THREAD

**Issue by ak-singla** [razorpay/razorpay-php#114]
I have found that there is not webhook for the subscription.authenticated, which restricts the verification of the start of trial period when the auth transaction is completed. 

Please help to understand how can I know that a particular subscription is authenticated.

**Comment by harman28** [comment]
Not related to this package. Please report this on the [support portal](https://razorpay.com/support/).

Subscription authentication is generally done on your own website. So you'd know when a particular subscription is authenticated since you'd have initiated that process yourself.
