### ISSUE TITLE
How to Verify Payment Signature after successful payment

### ISSUE THREAD

**Issue by MineshRai** [razorpay/razorpay-php#118]
Hi,
  I have integrated razorpay in my website, currently under test mode. The payment flow is working properly. But I am not able to verify the signature. I have added following code which is throwing NULL output. What to do???

```
<?php

require('razorpay/config.php');
require('razorpay/razorpay-php/Razorpay.php');

use Razorpay\Api\Api;

$api = new Api($api_key, $api_secret);

if ( ! empty( $_POST['razorpay_payment_id'] ) ) {

$attributes = array( 'razorpay_signature' => $_POST['razorpay_signature'], 'razorpay_payment_id' => $_POST['razorpay_payment_id'], 'razorpay_order_id' => $_SESSION['razorpay_order_id'] );

$order = $api->utility->verifyPaymentSignature($attributes);

var_dump($order);

}

?>
```

**Comment by harman28** [comment]
@MineshRai `verifyPaymentSignature` throws an exception when signature verification fails, and returns null otherwise. So it looks like your verification is succeeding.

This should ideally be in the README as well, I'll get it added. Will close this issue when done.

**Comment by MineshRai** [comment]
@harman28 But how to do error validation. Means if a payment gets failed customer should get message, for what reason his payment got failed... I want to display the specific error message...

**Comment by harman28** [comment]
@MineshRai Are you using [checkout.js](https://razorpay.com/docs/payment-gateway/web-integration/standard/)? If so, failures are already handled, as the customer is typically shown a retry button.

If you'd like to get more data about payment failures for your own internal tracking purposes, the [payment fetch APIs](https://razorpay.com/docs/api/payments/#fetch-a-payment) (`$api->payment->all` or `$api->payment->fetch` in this package) will share more details and specific error messages.

**Comment by RohitChattopadhyay** [comment]
I am using Payment Links API, successfully tested creation but signature matching is not working. It always returns `Signature did not match`
```
        $attributes = array(
            'razorpay_order_id' => getOrderID(($_GET['razorpay_invoice_id'])),
            'razorpay_payment_id' => $_GET['razorpay_payment_id'],
            'razorpay_signature' => $_GET['razorpay_signature']
        );        
        $api->utility->verifyPaymentSignature($attributes);
```
`getOrderID(($_GET['razorpay_invoice_id']))` correctly returns order_id which starts with *order_*.
the callback url is given and sends `'razorpay_order_id'  'razorpay_payment_id'  'razorpay_signature' `as GET request.
I have followed documentation/examples but still unable to correctly match the signatures.

**Comment by vinovsh** [comment]
i got this same error but patment was successfully captured please help

Hi,
I have integrated razorpay in my website, currently under test mode. The payment flow is working properly. But I am not able to verify the signature. I have added following code which is throwing NULL output. What to do???

<?php

require('razorpay/config.php');
require('razorpay/razorpay-php/Razorpay.php');

use Razorpay\Api\Api;

$api = new Api($api_key, $api_secret);

if ( ! empty( $_POST['razorpay_payment_id'] ) ) {

$attributes = array( 'razorpay_signature' => $_POST['razorpay_signature'], 'razorpay_payment_id' => $_POST['razorpay_payment_id'], 'razorpay_order_id' => $_SESSION['razorpay_order_id'] );

$order = $api->utility->verifyPaymentSignature($attributes);

var_dump($order);

}

?>

**Comment by RohitChattopadhyay** [comment]
@vinovsh 
You can follow this https://github.com/razorpay/razorpay-php/pull/147 if you are still facing the issue

**Comment by nilava** [comment]
Try this!

```
<?php

require('razorpay/config.php');
require('razorpay/razorpay-php/Razorpay.php');

use Razorpay\Api\Api;
use Razorpay\Api\Errors\SignatureVerificationError;

$api = new Api($api_key, $api_secret);
$success = false;
if ( ! empty( $_POST['razorpay_payment_id'] ) ) {

 try
    {
        $attributes = array(
            'razorpay_order_id' => $_SESSION['razorpay_order_id'],
            'razorpay_payment_id' => $_POST['razorpay_payment_id'],
            'razorpay_signature' => $_POST['razorpay_signature']
        );

        $api->utility->verifyPaymentSignature($attributes);
        $success = true;
    }
    catch(SignatureVerificationError $e)
    {
        $success = false;
        $error = 'Razorpay Error : ' . $e->getMessage();
    }

}

if ($success === true)
{
    $html = "Payment success/ Signature Verified";
}
else
{
    $html = "<p>Your payment failed</p>
             <p>{$error}</p>";
}
echo $html;
?>
```

**Comment by harman28** [comment]
Thanks for that @nilava , your sample code is very readable and self-explanatory. We should add it to our README :) Feel free to raise a PR if you can!

**Comment by nilava** [comment]
> Thanks for that @nilava , your sample code is very readable and self-explanatory. We should add it to our README :) Feel free to raise a PR if you can!

Hey, thanks, i already have a PR open for over a month fixing the Token Class issues. 
Try out the token function in the library, it wont work! I have fixed them and created a PR already.

**Comment by rohitkatiyar1984** [comment]
Thanks for this.. Saved me a lot of time..!!!

**Comment by Raghavendraprasad1** [comment]
> Try this!
> 
> ```
> <?php
> 
> require('razorpay/config.php');
> require('razorpay/razorpay-php/Razorpay.php');
> 
> use Razorpay\Api\Api;
> use Razorpay\Api\Errors\SignatureVerificationError;
> 
> $api = new Api($api_key, $api_secret);
> $success = false;
> if ( ! empty( $_POST['razorpay_payment_id'] ) ) {
> 
>  try
>     {
>         $attributes = array(
>             'razorpay_order_id' => $_SESSION['razorpay_order_id'],
>             'razorpay_payment_id' => $_POST['razorpay_payment_id'],
>             'razorpay_signature' => $_POST['razorpay_signature']
>         );
> 
>         $api->utility->verifyPaymentSignature($attributes);
>         $success = true;
>     }
>     catch(SignatureVerificationError $e)
>     {
>         $success = false;
>         $error = 'Razorpay Error : ' . $e->getMessage();
>     }
> 
> }
> 
> if ($success === true)
> {
>     $html = "Payment success/ Signature Verified";
> }
> else
> {
>     $html = "<p>Your payment failed</p>
>              <p>{$error}</p>";
> }
> echo $html;
> ?>
> ```



@nilava where it is found ..
require('razorpay/config.php')

**Comment by nilava** [comment]
Its a custom file you can create to store $api_key &  $api_secret or directly define them in a single file

**Comment by Raghavendraprasad1** [comment]
Thank you for your response
