### ISSUE TITLE
How to user razorpay_order_id in Signature Verification process

### ISSUE THREAD

**Issue by MineshRai** [razorpay/razorpay-php#122]
Hi,
   I have integrated RazorPay Test Mode in my website... Its working fine... I have added following code for signature verification:

```
$attributes = array( 'razorpay_signature' => $_POST['razorpay_signature'], 'razorpay_payment_id' => $_POST['razorpay_payment_id'], 'razorpay_order_id' => $_POST['razorpay_order_id'] );

$order = $api->utility->verifyPaymentSignature($attributes);
```

But I am bit confused as to which value I have to use for `razorpay_order_id` in above code. Means the `razorpay_order_id` generated through Order Api that is stored in session & database. Or the `razorpay_order_id` that is fetched automatically along with `razorpay_payment_id` and `razorpay_signature` after successful payment.

I know both the values will be same but for the sake of security is it ok to use id that is stored in session.

Please help me out to clear my confusion... Thanks...

**Comment by Mayur-Wadpalliwar** [comment]
@MineshRai Please use the order_id that you get as part of the create order response

**Comment by MineshRai** [comment]
@Mayur-Wadpalliwar  Thanks for your inputs. But https://github.com/razorpay/razorpay-php-testapp/blob/master/verify.php suggests that the razorpay order ID must come from a trusted source. hence will the id stored in session will be safe to use.

**Comment by Mayur-Wadpalliwar** [comment]
@MineshRai The order being stored in the session is the one you get in the create order response
