### ISSUE TITLE
Requests library missing

### ISSUE THREAD

**Issue by developerrito** [razorpay/razorpay-php#123]
You should either include the Requests lib in the package or change your code.

**Comment by harman28** [comment]
Hi @developerrito . Our [releases section](https://github.com/razorpay/razorpay-php/releases/tag/2.5.0) solves for this by giving you a zip file with all dependencies handled, i.e. Requests library includes. The other option is to install via composer, which handles dependencies for you.

Closing this issue for now, but please feel free to add more suggestions you may have.
