### ISSUE TITLE
Curl Error

### ISSUE THREAD

**Issue by tsdreddy** [razorpay/razorpay-php#124]
I am getting following error when i try to use razorpay php

Uncaught Requests_Exception: cURL error 28: Resolving timed out after 10000 milliseconds in  /public_html/members/vendor/rmccue/requests/library/Requests/Transport/cURL.php:422
Stack trace:
/public_html/members/vendor/rmccue/requests/library/Requests/Transport/cURL.php(177): Requests_Transport_cURL->process_response('', Array)
#1 /public_html/members/vendor/rmccue/requests/library/Requests.php(379): Requests_Transport_cURL->request('https://api.raz...', Array, Array, Array)
#2 /public_html/members/vendor/razorpay/razorpay/src/Request.php(56): Requests::request('https://api.raz...', Array, Array, 'POST', Array)
#3 /public_html/members/vendor/razorpay/razorpay/src/Entity.php(86): Razorpay\Api\Request->request('POST', 'https://api.raz...', Array)
#4 /public_html/members/vendor/razorpay/razorpay/src/Entity.php(15): Razorpay\Api\Entity->request('POST', 'orders/', Array)
#5/public_html/members/vendor/razorpay in /public_html/members/vendor/rmccue/requests/library/Requests/Transport/cURL.php on line 422

**Comment by peter279k** [comment]
It seems that this error is about cURL request timeout.

Do you try again later? Or it still has the same issue after trying same cURL request?

I think it's the temporary error and the remote API service is not response at that moment.

**Comment by MithileshHinge** [comment]
Hi I am getting the same issue, it is not related to internet speed or connection issues from my side. Reloading once or twice resolves it. But its happening frequently.

Could you please look into it?

**Comment by harman28** [comment]
> Reloading once or twice resolves it
This certainly seems to be a connectivity issue then. Closing this for not being related to the PHP package.

**Comment by MithileshHinge** [comment]
Update: This was an issue of our hosting, it would happen periodically so as to put a throttle on our number of requests perhaps? (We were using GoDaddy). I believe it's a deliberate measure put in place by GoDaddy. This issue hasn't arisen since we shifted to DigitalOcean.

**Comment by harman28** [comment]
Thanks for the update @MithileshHinge, good to know you aren't facing the issue now 👍
