### ISSUE TITLE
Missing Subscription Update function

### ISSUE THREAD

**Issue by vinaysudani** [razorpay/razorpay-php#127]
Function update is missing on subscription entity

https://razorpay.com/docs/subscriptions/api/subscriptions/#update-a-subscription

**Comment by cssjockey** [comment]
Hi, please add this function. Thanks.

**Comment by ankitdas13** [comment]
Hi @vinaysudani sorry for the delay but we already added this functions in our sdk . can you please check it out [doc](https://github.com/razorpay/razorpay-php/blob/master/documents/subscription.md#update-particular-subscription).

Closing this issue for now.
