### ISSUE TITLE
Move to guzzle

### ISSUE THREAD

**Issue by captn3m0** [razorpay/razorpay-php#13]
We want to move our HTTP backend to guzzle down the line. Things we need to take care of:
- [ ] Don't break the existing SDK
- [ ] How to handle the httplug requirement [https://packagist.org/packages/php-http/httplug]
- [ ] Should this be a major version upgrade?
- [ ] Decide between guzzle 5 and 6 (I'd prefer 6, but not everyone has upgraded there yet)
- [ ] If we go with 6, do we keep supporting the older requests releases?
- [ ] How to handle the razorpay-php.zip bundle we give out in our releases? This is important because we currently don't include the composer autoloader, but just the custom Requests autoloader, which only autoloads requests library. This helps us avoiding the entire composer dependency. However, guzzle probably will resolve to 10-15 dependencies which we need to autoload cleanly, even if the end-user is using the Razorpay.php file without using composer.

Assigning to @StSarc to look into this.

**Comment by Nyholm** [comment]
May I suggest not using Guzzle directly. Relying on an implementation is never good. That is why you should use HTTPlug which is an abstraction over libraries like Guzzle.

**Comment by captn3m0** [comment]
Makes sense. I need to read up a bit more on the nuance, but the idea was to use httplug.

**Comment by gaurav1068** [comment]
@nemo 

Should this be a major version upgrade?
I don't think so for the user nothing is changing, only internals are 

Decide between guzzle 5 and 6 -> Even I would prefer guzzle 6 
https://www.reddit.com/r/PHP/comments/37llgz/which_version_of_guzzle/
even for other projects either they have moved to 6 or planning to,

If we go with 6, do we keep supporting the older requests releases
can you clarify

guzzle 6 have 3 dependencies guzzlehttp/psr7, guzzlehttp/promises, psr/http-message

How to handle the httplug requirement
what do you mean by this ??

**Comment by captn3m0** [comment]
**Version**: I'm not entirely sure. If the upgrade is seamless, then minor upgrade should do. However, if people are likely to face dependency issues while upgrading, a major upgrade might make more sense.

**Old Releases**: If for some reason, someone is unable to upgrade, do we keep supporting the older releases? Or force people to upgrade?

**HTTPlug**: Using httpplug means that we can let the library users decide on a different implementation. httplug is an interface that says how to make requests. Various other libraries implement it, including guzzle. 
That way, if someone is using an older version of guzzle, or some other request library, it would still work with it.

**Comment by gaurav1068** [comment]
Version: let's decide on version at the end, as you mentioned if upgrade is seamless then minor upgrade or else major upgrade.

Old Releases: We should be supporting the older release, it doesn't make sense to force everyone to upgrade

HTTPlug: Do we want to give that much flexibility to users, debugging may be difficult. Your call, in my view, if we can restrict the user to a single library it is better.

**Comment by captn3m0** [comment]
The reason we can rely better on httplug is because it gives users flexibility to switch between implementations. This is important in case you have other libraries that rely on a specific guzzle version, for eg.

**Comment by captn3m0** [comment]
Aside: Requests 1.7 is now out: https://github.com/rmccue/Requests/releases

**Comment by ankitdas13** [comment]
@captn3m0 we have been using Request since the beginning ,and users also depend on it for updates as well. We will regularly add the updated Request. 

Closing for now . will reopen if needed
