### ISSUE TITLE
How to generate dynamic qr code in php using razorpay api 

### ISSUE THREAD

**Issue by sateeshmobikan** [razorpay/razorpay-php#134]
<?php

require('config.php');
require('razorpay-php/Razorpay.php');
session_start();

// Create the Razorpay Order

use Razorpay\Api\Api;

$api = new Api($keyId, $keySecret);
// Orders
$order = $api->order->create(array('receipt' => '123', 'amount' => 100, 'currency' => 'INR')); // Creates order
$orderId = $order['id']; // Get the created Order ID
$order = $api->order->fetch($orderId);
$payments = $api->order->fetch($orderId)->payments(); // Returns array of payment objects against an order
$bharatQR = $api->virtualAccount->create(array('receivers' => array('types' => array('qr_code')), 'description' => 'First QR code', 'notes' => array('receiver_key' => $keyId))); // Create Dynamic QR
echo $bharatQR;

error is 

Fatal error: Uncaught Razorpay\Api\Errors\BadRequestError: The requested URL was not found on the server. in F:\wamp64\www\inventrymanagement\razorpay\razorpay-php\src\Request.php:123 Stack trace: #0 F:\wamp64\www\inventrymanagement\razorpay\razorpay-php\src\Request.php(90): Razorpay\Api\Request->processError(Array, 400, Object(Requests_Response)) #1 F:\wamp64\www\inventrymanagement\razorpay\razorpay-php\src\Request.php(44): Razorpay\Api\Request->checkErrors(Object(Requests_Response)) #2 F:\wamp64\www\inventrymanagement\razorpay\razorpay-php\src\Entity.php(59): Razorpay\Api\Request->request('POST', 'https://api.raz...', Array) #3 F:\wamp64\www\inventrymanagement\razorpay\razorpay-php\src\Entity.php(15): Razorpay\Api\Entity->request('POST', 'virtualAccounts...', Array) #4 F:\wamp64\www\inventrymanagement\razorpay\razorpay-php\src\VirtualAccount.php(9): Razorpay\Api\Entity->create(Array) #5 F:\wamp64\www\inventrymanagement\razorpay\payment1.php(17): Razorpay\Api\VirtualAccount->create(Array) #6 {main} thrown in F:\wamp64\www\inventrymanagement\razorpay\razorpay-php\src\Request.php on line 123

**Comment by harman28** [comment]
Are you able to hit the API directly using the same credentials? Seems like your account is not configured to create virtual accounts.

**Comment by brnrajoriya** [comment]
Facing same issue.  "error": "The requested URL was not found on the server.",
Any Solution ?

**Comment by harman28** [comment]
`The requested URL was not found on the server.` is the error response the API returned when you do not have access to a feature, like virtual accounts or bharatQR. You can get these features enabled by reaching out through our [support portal](https://razorpay.com/support/), or via the chat option on your merchant dashboard.

**Comment by hari7261** [comment]
qr is small for kiosk @sateeshmobikan
