### ISSUE TITLE
OAuth access token expires, what error can I expect

### ISSUE THREAD

**Issue by zapling** [razorpay/razorpay-php#137]
I'm trying to figure out what kind of error that will be triggered when the Oauth access token expires, is it correct to assume its `ServerError`, if thats the case, is it possible to get a more specific error?

**Comment by harman28** [comment]
You should already be getting a readable error message, i.e. the `error.description` should be `The api key provided by you has expired and cannot be used. Please use correct key and secret.`

**Comment by zapling** [comment]
Okey correct me if I'm wrong, will it be a `ServerError` exception with the `message` being `The api key provided by you has expired and cannot be used. Please use correct key and secret.`?

On https://razorpay.com/docs/oauth/access/#token-expiry it says I'll get a `401`, is this also true when using this repo?

**Comment by harman28** [comment]
Sorry for the delay here, I hope this was sorted out for you. Noting a response here anyway in case someone else comes looking.

No, it shouldn't be a server error, it will be a 4xx, i.e. a `BadRequestError` in this repo. And yes, the response code will be 401, as returned by the API.
