### ISSUE TITLE
Razorpay ajax issue

### ISSUE THREAD

**Issue by vaibhav-iiit** [razorpay/razorpay-php#14]
I'm loading the razorpay form  by ajax. In ajax call it is directly calling '/pay/index' page instead of showing the razorpay gateway. 

**I'm Loading this by ajax call.** 

    ` <form action="/pay/index" method="POST" id="payForm">
          <script
            src="https://checkout.razorpay.com/v1/checkout.js"
            data-key="rzp_test_lQNUlfCzqCnq4h"
            data-amount="1111" 
            data-name="company-name"
            data-description="Enjoy savings and benefits of Premium Service"
            data-image="image-url"
            data-prefill.email="<?php echo $userEmail; ?>"
            data-prefill.contact="<?php echo $userMobile; ?>"
            data-theme.color="#00bbff"
          ></script>
            <input type="hidden" value="<?php echo $currentUrl; ?>"  name="redirectURL">
            <input type="hidden" value="3"  name="subscriptionId">
        </form>`
      <a class= js-make-payment-btn">Make Payment <i class="icon-arrow-right pay-right-arrow"></i> </a> 

**jquery to call razorpay:**

 `$('body').on('click', '.js-make-payment-btn', function (e) {
    e.preventDefault();
    e.stopPropagation();
    $('#payForm').submit();
  });`

**Comment by pronav** [comment]
Automatic checkout (where you pass options using data- attributes) is for very basic level of integration. In this case please take a look at [manual checkout](https://docs.razorpay.com/docs/checkout-form#manual-checkout) for more control over how you open checkout form.

**Comment by vaibhav-iiit** [comment]
@pronav Thanks ...issue solved by manual checkout

**Comment by FightWithCode** [comment]
I want to ask a question.

The **data-key** in script tag container the real merchant-key, which is clearly visible in Inspect Element.

Is that not harmful for security.
