### ISSUE TITLE
/payouts api throw a error

### ISSUE THREAD

**Issue by TsingXu430** [razorpay/razorpay-php#140]
<img width="705" alt="WX20191213-145558@2x" src="https://user-images.githubusercontent.com/17681100/70776713-ce446c00-1db8-11ea-9977-96599920e3fa.png">

**Comment by harman28** [comment]
Looks like your account isn't permitted to use this feature. Could you report this on our support portal so they can get this enabled for you?

**Comment by TsingXu430** [comment]
From what portal can I give feedback？
