### ISSUE TITLE
Omnipay

### ISSUE THREAD

**Issue by ahmed1886** [razorpay/razorpay-php#141]
Are you going to continue the development of [Omnipay](https://github.com/razorpay/omnipay-razorpay) package?

There are some forks that claim working but none works https://packagist.org/?query=razorpay%20omnipay

**Comment by harman28** [comment]
We're currently planning which plugin/packages we're going to pick up for stabilization and updates in the next 2 months. I'll see if Omnipay can be squeezed in as well. Thanks for the suggestion.
