### ISSUE TITLE
Check for errors while capturing payments

### ISSUE THREAD

**Issue by ZenPets** [razorpay/razorpay-php#148]
So I finally managed to integrate the PHP API in the project. And after a few tests, most things are working fine. However, is there anyway we can check for errors?

I am using the Slim framework and if an error occurs it simple shows "Slim Application Error". It does not show the actual errors. It logs them to the log file though. I tried setting the wrong Payment ID to test the error codes and the "Slim Application Error" is all I get.

The code I am using is:

```
<?php

use Razorpay\Api\Api;

/** CHECK THE PAYMENT STATUS **/
$app->get('/checkPaymentStatus', function ($request, $result) {
    
    $apiKey = $request->getParam('apiKey');
    $apiSecret = $request->getParam('apiSecret');
    $paymentID = $request->getParam('paymentID');

    $api = new Api($apiKey, $apiSecret);
    $payment = $api->payment->fetch($paymentID);
    $payment->capture(array('amount' => 5000, 'currency' => 'INR'));

    /* DECLARE AN ARRAY INSTANCE */
    $response = array();

    $error = $payment->error_code;
    print_r($payment->);

    /** SHOW THE RESULT **/
    $content_type = 'application/json';
    return $result->withStatus(200)
        ->withHeader('Content-type', $content_type)
        ->write(json_encode($response));
});
```

Your help is appreciated.

**Comment by harman28** [comment]
Some confusion here. The payment error code doesn't return the error you received while trying to capture the payment. When the `capture` function is called, if an error occurs, it is thrown in the form of an exception. You can catch these (try catch block for the specific error exception) and handle them however you see fit. You can also catch them all more generally (they are all children of `Razorpay\Api\Errors\Error` except signature verification) and handle them all identically.
