### ISSUE TITLE
Customer endpoint returns name as NULL.

### ISSUE THREAD

**Issue by irfnhm** [razorpay/razorpay-php#154]
The customer endpoint is returning name as NULL.  Below is one of the responses. Why is this happening?
`{

    "id": "cust_xxxxxx",

    "entity": "customer",

    "name": null,

    "email": "customer@merchant.com",

    "contact": "+91xxxxxxxxx",

    "gstin": null,

    "notes": [],

    "created_at": 1563864998

}`

**Comment by jitendra-1217** [comment]
Please share http request parameters(you can mask pii)

**Comment by irfnhm** [comment]
This is the request: 
`curl https://api.razorpay.com/v1/customers/cust_xxxxxxxxxxx -u rzp_test_xxxxxxxxxxxxx:xxxxxxxxxxxxxxxxxxx \ | json`

**Comment by irfnhm** [comment]
Found the issue. Thanks! @jitendra-1217
