### ISSUE TITLE
What if signature verification fails after successfull payment

### ISSUE THREAD

**Issue by duesXMachine** [razorpay/razorpay-php#156]
I am little confused in signature verification.If signature verification fails after successful payment then should that transaction be rolled back or what.Even if signature verification fails payment has been done.So what's the point

**Comment by jitendra-1217** [comment]
Are you talking about webhook signature verification?

**Comment by duesXMachine** [comment]
No..there is one last step in Razorpay Standard Checkout.
[https://razorpay.com/docs/payment-gateway/web-integration/standard/#step-5---verify-the-signature]

**Comment by jitendra-1217** [comment]
> If signature verification fails after successful payment then should that transaction be rolled back or what

You are right. If payment was successful it is done. The response that you receive in checkout  contains razorpay_payment_id, razorpay_order_id and razorpay_signature. Note that razorpay_signature is only available when you are using order system(see razorpay_order_id). 

Now if you have some more flows and you pass around this information to your own backend the signature is a way to verify that the razorpay_payment_id and razorpay_order_id attribute is in fact right and is not modified/malformed and can correctly assume that that order id has received this payment id.
