### ISSUE TITLE
Class redeclaration error with latest WordPress 4.6

### ISSUE THREAD

**Issue by hirenbhuva1993** [razorpay/razorpay-php#16]
Latest WP version 4.6 having same class 'request' so I think you are at right place to update the library that will work with WordPress.

**Comment by captn3m0** [comment]
Thanks for pointing this out. Our current Wordpress offering is the woocommerce plugin, which does not use the php package.

We'll be looking into this.

**Comment by hirenbhuva1993** [comment]
Hi,

Thank you for the prompt response, as we are using razorpay php library with our custom plugin, so we are facing issue with it.

I hope you can fix this in next release, or can you guide me how can i temporary fix this issue?

**Comment by captn3m0** [comment]
Can you point out the class that is clashing?

1. We have a `Razorpay\Api\Request` class that is namespaced, so should not clash
2. There is a `Requests` class (note the plural) at `libs/Requests-1.6.1/library/Requests.php` that shouldn't be clashing either.

Might be easier if you can point us to the plugin.

**Comment by hirenbhuva1993** [comment]
Yes, error is in Requests.php file (Fatal error: Cannot redeclare class Requests).

**Comment by captn3m0** [comment]
- From what I've read Wordpress uses the same requests library as we do (https://make.wordpress.org/core/2016/07/27/http-api-in-4-6/) with the very same version
- As such, you can just disable the requests autoloader in Razorpay.php and it should work

To do that, can you try commenting out lines [4-7](https://github.com/razorpay/razorpay-php/blob/master/Razorpay.php#L4-L7) in Razorpay.php and report back here if it works?

**Comment by hirenbhuva1993** [comment]
Yes after comment out that lines payment process is working fine. I would like to know that, is there any specific functionality implemented with Requests class. 

Thank you for the help.

**Comment by captn3m0** [comment]
We use the standard Requests library, release 1.6.1 (latest) and do not make any changes.

Closing this issue, as there is a very easy and clear workaround.
