### ISSUE TITLE
how to intrigate razorpay api

### ISSUE THREAD

**Issue by pvcdausa** [razorpay/razorpay-php#164]
razorpay api walllet ammount intrigate prosses 
help now

**Comment by harman28** [comment]
Hi @pvcdausa. Don't have enough info here to know what you're asking for. Will share some useful links:
- Supported wallets: [Link](https://razorpay.com/docs/payment-methods/wallets/)
- Easy integrations: [Link](https://razorpay.com/integrations/)
- Support portal for integration queries: [Link](https://razorpay.com/support/)
