### ISSUE TITLE
Deprecated implode (Passing glue string after array is deprecated) in Php 7.4

### ISSUE THREAD

**Issue by chiragkatare** [razorpay/razorpay-php#166]
When creating order , it fails with message _implode(): Passing glue string after array is deprecated. Swap the parameters_

Seems to be the issue in *rmccue/requests* package , Please upgrade the package

**Comment by harishdurga** [comment]
Facing the same issue. Not sure how to proceed.

**Comment by ankitdas13** [comment]
@chiragkatare sorry for the delay . This issue has been fixed in the updated rmccue/request package and we have checked this issue and we didn't get this error while creating an order. can you please update your php version in PHP v7.4 or above and use the latest sdk .
