### ISSUE TITLE
Support for Razorpay X endpoints?

### ISSUE THREAD

**Issue by vaibhavpandeyvpz** [razorpay/razorpay-php#169]
Do you have any recent plans for first-party library support for the newly introduced Razorpay X APIs?

**Comment by ankitdas13** [comment]
Hi @vaibhavpandeyvpz sorry for the delay 

thank you for bringing this to our attention. i will forward this to the integration team.

Closing this issue for now let us know if you need any help

**Comment by technoknol** [comment]
it's been 2 years since this issue was open. Any update on this?
