### ISSUE TITLE
Razorpay - Codeignetor

### ISSUE THREAD

**Issue by dipakdkale** [razorpay/razorpay-php#176]
Hi there

Since lots of developers are using frameworks nowdays can you please make codes specific to php frameworks like codeignetor and laravel will be helpful. Thanks in advance

**Comment by ankitdas13** [comment]
Hi @dipakdkale sorry for the delay . with help of this [documentation ](https://razorpay.com/docs/payments/payment-gateway/web-integration/standard/build-integration/#api-sample-code) you can easily integrate razorpay in any frameworks , for laravel 
1. Install Razorpay Package
2.  Add Razorpay instance in controller [codesnippet](https://razorpay.com/docs/payments/payment-gateway/web-integration/standard/build-integration/#api-sample-code)
3. Add this pay button [codesnippet ](https://razorpay.com/docs/payments/payment-gateway/web-integration/standard/build-integration/#code-to-add-pay-button) in view . 

let us know if you need any help
