### ISSUE TITLE
Create Order: implode(): Passing glue string after array is deprecated. Swap the parameters

### ISSUE THREAD

**Issue by khanujasunny** [razorpay/razorpay-php#178]
Unable to create a new order using laravel and razorpay-php
PHP version: 7.4.7
Laravel: 7.20.0
Installed: composer require razorpay/razorpay:2.* (in a newly created laravel project)

Code snippet:

```
        $api = new Razorpay\Api\Api(config('custom.razor_key'), config('custom.razor_secret'));
        $order  = $api->order->create(array('receipt' => 'RandomNumber', 'amount' => 150, 'currency' => 'INR')); // Creates order
        return response(['data' => $order, 'message' => 'Create order works'], 200);
```

Return(exception message from Handler.php):

```
{
    "errors": {
        "status": 0,
        "message": "implode(): Passing glue string after array is deprecated. Swap the parameters"
    }
}
```

**Comment by khanujasunny** [comment]
I was able to fix for mine following the below steps:

open file: `yourApp\vendor\rmccue\requests\library\Requests\Transport\fsockopen.php` - Line number 195

Replace: `$out .= implode($headers, "\r\n") . "\r\n";`


With: `$out .= implode("\r\n", $headers) . "\r\n";`

Of course, you will need to do this every time you install dependencies - hope they come up with a fix.

**Comment by ankitdas13** [comment]
@khanujasunny sorry for the delay . This issue has been fixed in the updated rmccue/request package and we have checked this issue and we didn't get this error while creating an order. can you please update your php version in PHP v7.4 or above and use the latest sdk .

Closing this issue for now . let us know if you need any help
