### ISSUE TITLE
Laravel 

### ISSUE THREAD

**Issue by pronet79** [razorpay/razorpay-php#180]
Hello, 
I am new in laravel. Could anyone tell me where we will put the followings:
1) Razorpay.php page
2) Src and Test folder 
in laravel. Thanks in advance

**Comment by CirkaN** [comment]
Firstly go to your project root and run composer installation

composer require razorpay/razorpay

Than you import class in your Controller

For example, I think it goes

use razorpay\razorpay

Look at documentation for that if I am wrong, and that's it you can use it in your controller.

Happy Coding!

**Comment by pronet79** [comment]
Hello @CirkaN, I have few specific question about Razorpay. These are as follows:-
1) If you see the URL(https://razorpay.com/docs/payment-gateway/server-integration/php/test-app/), there has a link to download Razorpay PHP Sample App. If you use this app , you will see first create an order then take payment on that order automatically and after payment it shows payment status is Captured.
I also create the appllication using  javaScript in laravel. My code is as follows:
var options = {
			   "key": "rzp_test_XXXXXXXXXXXXXX",
			   "amount": (totalAmount*100), 
			   "name": "AAAAA",
			   "description": "BBBBBB",
			   "currency": "INR",
			   "receipt":"Receipt #20",
			   "id":lead_id,
			   "status":"created",
			    "image": "logo_sm.png",
			   "prefill": {
							name: cfull_name,
							email:cemail,
							contact:cphone
							},
				"theme": {
							color: '#b9a76e'
						  },
			   "handler": function (response){
					 $.ajax({
					   url: 'pay-success',
					   type: 'post',
					   dataType: 'json',
					   data: {
						razorpay_response:response,   
						razorpay_payment_id: response.razorpay_payment_id , 
						 totalAmount : totalAmount ,cfull_name : cfull_name,cphone:cphone,
						 lead_id:lead_id,
					   }, 
					   success: function (msg) {
			  				   window.location.href = 'booking-final';
					   }
				   });
				 
			   },
			  "prefill": {
				   "contact": cphone,
				   "email": cemail,
			   },
			   "theme": {
				   "color": "#528FF0"
			   }
			 };
			 var rzp1 = new Razorpay(options);
			 rzp1.open();
			 e.preventDefault();
 It effect the payment in Transaction tab of razorpay but shows payment status not captured. It did not generate order id. 
2) I want to create a functionality that from my system if i press a button then Razorpay send payment link and if payment done then it effect my application. Please help me. 
Thanks in advance.
