### ISSUE TITLE
BAD_REQUEST_ERROR Payment blocked as website does not match registered website(s)

### ISSUE THREAD

**Issue by bharathbiju** [razorpay/razorpay-php#184]
when i started razorpay in livemode , my payments become failed and i get this error in my dashboard .
 sorry if am posting  this in the  wrong repo
It would be great if someone could reply

**Comment by savita1378** [comment]
hi did you get the solution . i am also facing the same issue

**Comment by ankitdas13** [comment]
@savita1378 @bharathbiju sorry for the delay is this issue is resolved ? 
seems like the live mode feature is not activated in your accounts . if this issue has been resolved please let us know.

**Comment by ankitdas13** [comment]
Closing this ticket for now . if you still getting this issue then you can reopen this issue
