### ISSUE TITLE
BUG: Amount exceeds maximum amount allowed.

### ISSUE THREAD

**Issue by nguyendachuy** [razorpay/razorpay-php#192]
https://razorpay.com/docs/payment-pages/faqs/

**13. What is the maximum payment amount allowed per transaction on a Payment Page?
By default, a customer can make a maximum payment of ₹5,00,000. This can be raised by raising a request with Razorpay Support.** 

I want to pay the customer an amount of 30000 INR

When I make an order in the amount of 30000 * 100 = 300000
=> **I got the error again, Amount exceeds maximum amount allowed.**

When I make an order in the amount of 30000

=> **In order created only 300 INR**

How do I make 30000 INR in order?

**Comment by ankitdas13** [comment]
@nguyendachuy We have tried creating an order of 30000 Indian rupees, and it has been created. could you please try again let us know if this occurs again.

**Comment by VishwasTamta** [comment]
It's not working, saying the same error mentioned above

**Comment by rudrcodes** [comment]
I've been trying Razorpay in test mode and being getting the same error still, is there any workaround it.
TechStack : ReactJS , NodeJS

**Comment by ronijaat** [comment]
> I've been trying Razorpay in test mode and being getting the same error still, is there any workaround it. TechStack : ReactJS , NodeJS

any solution for this?
