### ISSUE TITLE
Retrieving token status throws error

### ISSUE THREAD

**Issue by ghost** [razorpay/razorpay-php#195]
Hello team,

For emandate verification I tried to check token status of a customer Using below api call. But it throws error that function isn’t available.

$token  = $api->customer->token()->fetch($tokenId);

Error message: 
Uncaught Error: Call to undefined method Razorpay\Api\Customer::token()

Error Response: 
Notice: Undefined index: token in C:\xampp\htdocs\razorpay\api\src\Resource.php on line 40

Fatal error: Uncaught Error: Call to a member function fetch() on null in C:\xampp\htdocs\razorpay\test.php:17 Stack trace: #0 {main} thrown in C:\xampp\htdocs\razorpay\test.php on line 17

Kindly help me. I tried with both 1.6 and 1.7 version

**Comment by VeeK727** [comment]
You should share a complete reproducible example.

**Comment by Approlabs** [comment]
> complete reproducible example

What do you mean by complete reproducible example. 

Mentioned function in this document throws such error. instead of $tokenId replacing a token from my razorpay dashboard and run the code this error throws. Thats all my doubt.

**Comment by ankitdas13** [comment]
There is something wrong with the code you shared . can you please install the latest sdk and use this code snippet
`$api->customer->fetch($customerId)->tokens()->fetch($tokenId);`
or you can also check this [documentation ](https://github.com/razorpay/razorpay-php/blob/master/documents/token.md) for all token related api. 

Closing for now let us know if need any help
