### ISSUE TITLE
Connection TimeOut api.razorpay.com

### ISSUE THREAD

**Issue by bhagchandani** [razorpay/razorpay-php#199]
Laravel logs the following error.

Requests_Exception: cURL error 28: Failed to connect to api.razorpay.com port 443: Connection timed

But it only happens in 1 out of 10 transactions. Can someone suggest what can be the issue?

**Comment by ankitdas13** [comment]
Hi @bhagchandani could you please let us know if this issue still persist ?

Closing this issue for now but if you are still experiencing this issue , please repen it
