### ISSUE TITLE
API Documentation Issues

### ISSUE THREAD

**Issue by NitinMaaraj** [Razorpay/razorpay-php#2]
Today i tested both Repositories

1. https://github.com/Razorpay/razorpay-php-testapp
2. https://github.com/Razorpay/razorpay-php

I hope this is some sort of documentation issue

Here - https://github.com/Razorpay/razorpay-php-testapp/blob/master/charge.php
I found out this code to initiate Razorpay API

use Razorpay\Api\Api;
//Use your key_id and key secret
**$api = new Api('rzp_test_1DP5mmOlF5G5ag', 'thisissupersecret');**

and this code works fine for me

But here - https://github.com/Razorpay/razorpay-php

use Razorpay\Api\Api
**$api = new Razorpay($api_key, $api_secret);**

This method gives me following error 
**Fatal error:** Class **'Razorpay' not found in /opt/lampp/htdocs/razorpay/index.php on line 38**

**Comment by shashankkumar** [comment]
Fixed. Thanks for reporting.
