### ISSUE TITLE
Recurring payment by token

### ISSUE THREAD

**Issue by khurshed** [razorpay/razorpay-php#203]
Is there any function to deduct amount (make payment ) by customer's token.
please help.

**Comment by khurshed** [comment]
I am able to this by dashboard but I want to Implement this by API.
I am using laravel.

**Comment by ankitdas13** [comment]
Hi @khurshed you can use recurring payment api 
For your reference, here is some [documentation](https://razorpay.com/docs/payments/recurring-payments/apis/) you can get all recurring payments APIs here. let us know if you need any help
