### ISSUE TITLE
How to add offers?

### ISSUE THREAD

**Issue by akshkgd** [razorpay/razorpay-php#205]

**Comment by ankitdas13** [comment]
@akshkgd In addition to creating orders, subscriptions, and payment links, you can add offers . you can check this documentation for more info
[Payment link](https://razorpay.com/docs/api/payments/payment-links/offers/#step-2-pass-offer_id-in-payment-link-create)
[Order](https://razorpay.com/docs/payments/payment-gateway/affordability/offers/standard-integration/#step-1-create-an-offer-from-razorpay-dashboard)
[Subscription](https://razorpay.com/docs/api/payments/subscriptions/#create-a-subscription)
