### ISSUE TITLE
Does the test API keys support international currencies

### ISSUE THREAD

**Issue by abishekmuthian** [razorpay/razorpay-php#206]
My  razorpay account has international payments enabled through PayPal.

I'm testing the subscription API using test API keys, which leads to the following anomalies.

**Creating a plan**

For any amount < 50.

```
{
  "period": "monthly",
  "interval": 1,
  "item": {
    "name": "Ideator",
    "amount": 49,
    "currency": "USD",
    "description": "Monthly subscription"
  }
}
```

```
{
    "error": {
        "code": "BAD_REQUEST_ERROR",
        "description": "The amount must be at least $0.5",
        "field": "amount"
    }
}

```

For any amount >= 50

```
{
  "period": "monthly",
  "interval": 1,
  "item": {
    "name": "Ideator",
    "amount": 50,
    "currency": "USD",
    "description": "Monthly subscription"
  }
}
```

```
{
    "error": {
        "code": "BAD_REQUEST_ERROR",
        "description": "Currency provided is not supported",
        "field": "currency"
    }
}
```

Expected behavior : Plan should be created for a supported currency.

**Comment by ankitdas13** [comment]
@abishekmuthian i have tried to create plan with same params you mention in description and its working . may be you dont have this feature enabled.

<img width="555" alt="Screenshot 2022-09-02 at 2 57 00 PM" src="https://user-images.githubusercontent.com/89454448/188138372-7b117ca7-2a38-4308-8d57-87a6f1a3062a.png">
