### ISSUE TITLE
Redirect Checkout

### ISSUE THREAD

**Issue by phpspider** [razorpay/razorpay-php#207]
Do you have Redirect Checkout option? e.g. I will submit a form with required values and customer should redirected to Razorpay checkout page.

**Comment by matheusliraofficial** [comment]
No, there is only a javascript code to execute the checkout form on the frontend

**Comment by gurusami** [comment]
Shouldn't such an option be the important one?  

I think customers would be more comfortable if they know that the credit card details are being submitted to the URL "https://razorpay.com" website.  By having this javascript checkout button, the customer cannot see "https://razorpay.com" in the browser address bar.  And it wouldn't give them confidence about who is really collecting the information.  Correct me if I am wrong.

**Comment by phpspider** [comment]
I've found it on Razorpay website.
https://razorpay.com/docs/payments/payment-gateway/web-integration/hosted/
