### ISSUE TITLE
Error while trying to do recurring payments

### ISSUE THREAD

**Issue by matheusliraofficial** [razorpay/razorpay-php#209]
I was doing the integration of my system with razorpay but only "one time payments" are working, when I try to execute the function to do "recurring payments" I got this error message:

The requested URL was not found on the server

**Comment by ankitdas13** [comment]
@matheusliraofficial for recurring payments use this [documentation](https://razorpay.com/docs/payments/recurring-payments/apis/)  you can get all recurring payments APIs here. let us know if you need any help
