### ISSUE TITLE
BAD_REQUEST_ERROR Payment blocked as website does not match registered website(s)

### ISSUE THREAD

**Issue by savita1378** [razorpay/razorpay-php#210]
when i tested razorpay in test mode then it was working fine but when  started razorpay in livemode  I got this error in my dashboard .
![image](https://user-images.githubusercontent.com/10096550/110631540-a2d34b80-81cc-11eb-9eac-a5a3c4b651c8.png)

It would be great if someone could reply

**Comment by ImranVaani** [comment]
Same issue with me

**Comment by ankurgubbins** [comment]
same issue with

**Comment by ankurgubbins** [comment]
please react to above comment and help!!

**Comment by mansurishahrukh007** [comment]
I am getting same error

**Comment by ankitdas13** [comment]
@savita1378 could please check that you have live mode enabled or not and please use the latest php sdk . if you are still getting this issue please let us we know.

Closing this issue for now
