### ISSUE TITLE
Wrong display amount for international currency

### ISSUE THREAD

**Issue by alkesh211** [razorpay/razorpay-php#211]
![Selection_144](https://user-images.githubusercontent.com/9250182/112637909-ae797000-8e64-11eb-90c8-af1080e692e5.png)
I am getting an issue to display amount of 1000 EURO, while actual transaction amount goes for payment of 10 EURO.

We have already processed amount of 10 EURO, which displays 1000 EURO.

Following is the code to process and display amount:

$currencyAmount = 10;
$displayCurrency = 'EUR';

    $orderData = [
        'receipt'         => 3456,
        'amount'          => (int)$currencyAmount * 100, // 2000 rupees in paise        
        'currency'        => $displayCurrency,
        'payment_capture' => 1 // auto capture
    ];

Here, transaction amount is going to proper with 10 EUR while issue is having only with displaying amount of 1000 EUR in place of 10 EUR

**Comment by chan2020** [comment]
I am also experiencing the same issue.

**Comment by ankitdas13** [comment]
@alkesh211 @chan2020  This issue has been fixed i have checked this from my side and it showing correct amount

<img width="1222" alt="Screenshot 2022-09-02 at 1 49 36 PM" src="https://user-images.githubusercontent.com/89454448/188097172-0a5afae4-a4a0-4c12-bc8d-98a9d8509a7c.png">

Closing this issue for now let me know if you are still getting this issue
