### ISSUE TITLE
   Getting error while creating Order on php7.4

### ISSUE THREAD

**Issue by jj-theInvincible** [razorpay/razorpay-php#215]
"message": "implode(): Passing glue string after array is deprecated. Swap the parameters"
   "file": "/var/www/prodot/backend/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php"
I know it's issue with the rmccue but why isn't razorpay using Guzzle?

**Comment by ankitdas13** [comment]
@jj-theInvincible we apologize for the delay . we have checked this issue and we didn't get this error while creating an order. can you please update your php version in PHP v7.4 and use the latest sdk .

For moving rmccue to guzzle it will be a major change and break the existing sdk but still i will discuss this with the integration team.

Closing this issue for now. let us know if you need any help
