### ISSUE TITLE
unable to procced payment in test mode in Angular

### ISSUE THREAD

**Issue by sayyedbasit75** [razorpay/razorpay-php#216]
when i enter dummy card detail it give error

**{
error: {
code: "BAD_REQUEST_ERROR",
description: "Please do not provide your secret on public sided requests",
source: "NA",
step: "NA",
reason: "NA",
metadata: { }
}
}**

can some one help me how to solve this error

**Comment by lethal10010** [comment]
did you find the solution?

**Comment by sayyedbasit75** [comment]
> did you find the solution?

No I Not Found Any Solution

**Comment by ankitdas13** [comment]
@sayyedbasit75 @lethal10010 sorry for the delay can you please provide the code snippet .

**Comment by ankitdas13** [comment]
Closing this ticket for now . if you still getting this issue then you can reopen this issue .
