### ISSUE TITLE
v2.6.1 Invalid module, can't install or update

### ISSUE THREAD

**Issue by hitinder** [razorpay/razorpay-php#222]
@ramth05   Here we go. The latest version 2.6.1 isn't working

![image](https://user-images.githubusercontent.com/9841229/117104422-c4901f80-ad84-11eb-84ad-4b2de15d9693.png)

**Comment by ramth05** [comment]
@hitinder , It's PHP SDK updates. We haven't upgraded to prestashop release. Please wait for sometime. Will update new sdk and provide new release.
