### ISSUE TITLE
Compatibility with PHP 8

### ISSUE THREAD

**Issue by isaumya** [razorpay/razorpay-php#227]
Has the API been tested with PHP 8? As we are actively using PHP 8, wanted to make sure the API is PHP 8 compatible.

**Comment by Whip** [comment]
Nope. Deprecation notice sources needs to be updated.

**Comment by ankitdas13** [comment]
@isaumya these versions [v2.8.3](https://github.com/razorpay/razorpay-php/releases/tag/v2.8.3) & [v2.8.4](https://github.com/razorpay/razorpay-php/releases/tag/v2.8.4) are compatible with php 8.0 . let me know if you need any help

**Comment by isaumya** [comment]
@ankitdas13 well, this message was from last year. Now I need to know if it is compatible with PHP 8.1. Please do let me know if the package is compatible with PHP 8.1.

**Comment by ankitdas13** [comment]
@isaumya Yes, it is compatible with PHP 8.1 as well

**Comment by isaumya** [comment]
Hey, @ankitdas13 now that's good news... Thanks for the confirmation.
