### ISSUE TITLE
Google Pay or Phone Pay or Paytm Pay API Checkout

### ISSUE THREAD

**Issue by blpraveen** [razorpay/razorpay-php#234]
I have a customer who have google pay or phone pay or paytm  account they give the details of phone number.

Now I need to withdraw the amount from there google pay or phone pay or paytm  account without using payment_link.

I could not find it in API Documentation . I want to know if this possible.

Is it possible with Razor pay API payment gateway integration.

I found this link useful But it is using JavaScript. can I do it in using  [Razor PAY PHP SDK][1] 
[Google Pay Checkout using Razor Pay][2]

Same way is it possible Phone Pay and Paytm Pay using Razor Pay

  [1]: http://composer%20require%20razorpay/razorpay
  [2]: https://razorpay.com/docs/payments/payments/payment-methods/upi/google-pay/custom-checkout/

**Comment by ankitdas13** [comment]
@blpraveen from server-side (Razorpay sdk) you can use this [api](https://github.com/razorpay/razorpay-php/blob/master/documents/payment.md#create-payment-json) or you can also check this [documentation](https://razorpay.com/docs/payments/payment-gateway/s2s-integration/json/v2/build-integration/cards) if want to payment through `card` , `netbanking` or `UPI` . but you can't use checkout without javascript. 

Closing this issue for now let us know if you need help.
