### ISSUE TITLE
Subscription API Call from php

### ISSUE THREAD

**Issue by homeassiist** [razorpay/razorpay-php#237]
Hi, we have difficulty calling subscription related api. We are calling https://api.razorpay.com/v1/subscription.  A code snippet to do this will help us greatly. 

Thank you.

**Comment by ankitdas13** [comment]
Hi @homeassiist sorry for the delay . you can use this [documentation](https://github.com/razorpay/razorpay-php/blob/master/documents/subscription.md) for subscription related api .

Closing this issue for now.
