### ISSUE TITLE
Payment Link edit not working 

### ISSUE THREAD

**Issue by ramth05** [razorpay/razorpay-php#260]
Getting error like
`incorrect JSON object received - faulty key: expire_by`

**Comment by ankitdas13** [comment]
Hi @ramth05 this issue has been fixed in this [PR](https://github.com/razorpay/razorpay-php/pull/257/files#diff-a14d738dc93ab45366af33889d21fdf591b289621d785dc6391f4863add04312L62) .

Closing this issue for now
