### ISSUE TITLE
Issue on addAllowedPayer on Smart Collect

### ISSUE THREAD

**Issue by ashishbudhraja** [razorpay/razorpay-php#275]
Hi,

When I am trying to add Payers to Smart Collect API, i am getting this issue

types is/are not required and should not be sent

**Comment by ankitdas13** [comment]
Hi @ashishbudhraja can you please use this code snippet for addAllowedPayer
`$api->virtualAccount->fetch($virtualId)->addAllowedPayer(array('type' => 'bank_account','bank_account' => array('ifsc'=>'UTIB0000013','account_number'=>'914010012345679')));` 

please let us know if this issue persists
