### ISSUE TITLE
The release package contains the hidden .git directory

### ISSUE THREAD

**Issue by gurusami** [razorpay/razorpay-php#286]
I downloaded the latest razorpay-php.zip file.  I noticed that it is containing .git and .github directories.  I think these are not needed in the release package.  Can you please remove such unwanted directories from the release package?

**Comment by ankitdas13** [comment]
@gurusami I checked the last four versions but I didn't find the .git and .github directories.

Closing this issue for now , but if you have any other suggestions, please let me know.
