### ISSUE TITLE
Compatiblity problem with WP

### ISSUE THREAD

**Issue by zimdin12** [razorpay/razorpay-php#290]
from version 2.8.3 I am getting error: 
Uncaught TypeError: WP_HTTP_Requests_Response::__construct(): Argument #1 ($response) must be of type Requests_Response, WpOrg\Requests\Response given, called in [SiteDir]\web\wp\wp-includes\class-http.php on line 397
thrown in [SiteDir]\web\wp\wp-includes\class-wp-http-requests-response.php on line 42

Problem is prob connected with rmccue/requests.
saddly I didn't have much more time to investigate it. So I fixed razorpay version to 2.8.2.

**Comment by ankitdas13** [comment]
@zimdin12 when we are trying to replicate this error. it working fine for me do let me know if you need any help


https://user-images.githubusercontent.com/89454448/187213476-a755e49f-7d31-44cb-8fae-c389168e4044.mov
