### ISSUE TITLE
what's the minimum PHP version support

### ISSUE THREAD

**Issue by Thavarajan** [razorpay/razorpay-php#294]
Hi team,
 In the readme, it was denoted as  PHP 7.3 as a minimum version but in 
composer JSON it was denoted as  5.3.0
Hope the composer json need to be updated,

Please clarify on this

**Comment by ankitdas13** [comment]
@Thavarajan We recommend using PHP 7.4 until version `v2.82` & you must upgrade your PHP in 8.0 if you are using the latest version, `v2.8.4`. In the latest version, we have already updated the composer
