### ISSUE TITLE
USE without Namespace for frameworks like Codeigniter,Cakephp

### ISSUE THREAD

**Issue by NitinMaaraj** [razorpay/razorpay-php#3]
Frameworks like **Codeigniter, CakePHP** do not support **NAMESPACES** in class files how can this be used in such environment ??

Currently i am trying Razorpay Integration in CakePHP 2.3.0 but this class is not working since CakePhp do not support namespaces in classes..

I hope this gets ready for such Frameworks since CakePhp and Codeigniter are highly used for developing web applications

**Comment by shashankkumar** [comment]
What PHP version are you using?

**Comment by NitinMaaraj** [comment]
**PHP Version 5.5.15**

System : 	Linux localhost 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:14:51 UTC 2015 i686

**Comment by shashankkumar** [comment]
The support for namespaces is provided by PHP language itself from version 5.3+ and doesn't depend on the framework. It will work with CakePHP as well as Codeigniter.

**Comment by NitinMaaraj** [comment]
**Fatal Error**

**Error: syntax error, unexpected 'use' (T_USE)**
File: /opt/lampp/htdocs/notified-appui/app/Controller/PlansController.php
Line: 54

I am getting this error after successfully including Razorpay.php file in my Controller File

**Comment by shashankkumar** [comment]
Can you paste a snapshot of the relevant code here?
Also, the 'use' statement comes at the top of the file after namespace declaration.
See this - http://php.net/manual/en/language.namespaces.importing.php

**Comment by NitinMaaraj** [comment]
AS i already said PHP supports NAMESPACEs but Cakephp 2.x dont support using namespaces because of its structure..

Here is a snapshot of my code 
/* ---------------------------------- */
<?php
App::uses('AppController', 'Controller');
**App::import('Vendor', 'Razorpay', array('file' => 'Razorpay/Razorpay.php'));**

class PlansController extends AppController {

public function index() {            
            ///Configure::write('debug',2);            
            $this->layout = 'user';            
//            $path = APP . 'Vendor' . DS . str_replace('\\', DS, $class) . '.php';
//            if (file_exists($path)) {
//                include $path;
//            }
//            
//            include_once(APP.'Vendor'.DS.'Razorpay'.DS.'Razorpay.php');
//            
            use Razorpay\Api\Api;    
            $api = new Api('rzp_test_KEY', 'rzp_test_secret');                        		
	}
}

**Comment by shashankkumar** [comment]
Take a look here - https://forums.tokbox.com/supported-server-api/php-cakephp-namespace-issue-t43277
Also, read about namespaces to understand you can use it better.

**Comment by NitinMaaraj** [comment]
OK thanks for the link..
I will try it soon .. but will be using CURL method described in API for now..
Thanks

**Comment by shashankkumar** [comment]
I will recommend using the API, it handles the edge cases better and you can update it when we release new features and bug-fixes. Once you get to know namespaces, it's pretty easy to use like any other standard language feature.

**Comment by NitinMaaraj** [comment]
Completed the Razorpay Payment integration in my app just now..

here is the code for doing it in Cakephp without including the Razorpay API Class..
This uses Cakephp HttpSockets..
Hope this will help other developers working on Cakephp and Razorpay



<?php
App::uses('AppController', 'Controller');
App::uses('HttpSocket', 'Network/Http');

class PlansController extends AppController {

public function thankyou(){

$socket = new HttpSocket();
$socket->configAuth('Basic', **API_KEY**, **API_SECRET**);

$data = array('amount' => **AMOUNT**);
$payment_id = **PAYMENT_ID**;

 $payment = $socket->post('https://api.razorpay.com/v1/payments/'.$payment_id.'/capture',$data);

 if($payment->code == 200){
                        $params = json_decode($payment->body); 
                        debug($params);
                    }
  }
}

?>

NOTE -  replace text in BOLD with your own runtime parameters

**Comment by shashankkumar** [comment]
This works too! Nice :)
However, I would really prefer if you can make the API work. It's not too difficult.

**Comment by NitinMaaraj** [comment]
yeah sure i will try it in my next app.. i was time bound so used this workaround.. ;)
