### ISSUE TITLE
Get a BAD_REQUEST_ERROR on live mode with laravel 9.

### ISSUE THREAD

**Issue by dev-agam** [razorpay/razorpay-php#328]
Error : **BAD_REQUEST_ERROR**
           _Your payment was not successful as this Seller is not allowed to accept payments.
            We suggest not going ahead with this transaction._
Error Source : Internal
Error Step : payment_initiation
Error Reason : payment_risk_check_failed

I'm integrating the payment gateway with laravel 9 and getting the above error on live mode, but on test mode, it's working fine.

**Comment by ankitdas13** [comment]
@dev-agam This is not an issue of sdk. if its working in test mode then it should also work in live mode. might be you dont have live activated account. let us know if you still facing this issue .
