### ISSUE TITLE
Load Requests class conditionally

### ISSUE THREAD

**Issue by ravinderk** [razorpay/razorpay-php#33]
Currently, I am working on WordPress project and it has this class in core, so conflict will occur.

For Ref:
https://github.com/WordPress/WordPress/blob/master/wp-includes/class-requests.php
https://github.com/razorpay/razorpay-php/blob/master/Razorpay.php#L4

```
// Custom Fix: WordPress also has Requests class.
if( ! class_exists( 'Requests' ) ) {
	// Include Requests
	require_once __DIR__.'/libs/Requests-1.6.1/library/Requests.php';
}
```

Note: Can we also update `Requests` lib version
For ref:
https://github.com/WordPress/WordPress/blob/master/wp-includes/class-requests.php#L91
https://github.com/razorpay/razorpay-php/blob/master/composer.json#L32

**Comment by captn3m0** [comment]
This is a known issue, and since we use the same Requests lib, there is an easy fix, documented at https://github.com/razorpay/razorpay-php/issues/16
