### ISSUE TITLE
Payment Link API issue occur

### ISSUE THREAD

**Issue by kirankumarmitnas** [razorpay/razorpay-php#360]
### Steps to reproduce the behavior

$api = new Api($paymentGatewayKey,$paymentGatewaySecret);
$result=$api->paymentLink->all();

1.  **razorpay\razorpay\src\Request.php**
 protected function throwServerError($body, $httpStatusCode)
 {
        $description = "The server did not send back a well-formed response. " . PHP_EOL .
                       "Server Response: $body";
		throw new Errors\ServerError($description,ErrorCode::SERVER_ERROR,$httpStatusCode);	
  }
Error is it  Array to string conversion on above code.
because its take by default take order class as child class on file bellow file name 
2.**razorpay\razorpay\src\Entity.php**
 protected function getEntityUrl()
  {
        $fullClassName = get_class($this);
        $pos = strrpos($fullClassName, '\\');
        $className = substr($fullClassName, $pos + 1);
        $className = $this->snakeCase($className);
        return $className.'s/';
   }
  this function return **order** class of the child class.but here we pass **$api->paymentLink->all();**.it should return paymentLink as child class.

### Expected behavior

$api = new Api($paymentGatewayKey,$paymentGatewaySecret);
$result=$api->paymentLink->all();

1.  **razorpay\razorpay\src\Request.php**
 protected function throwServerError($body, $httpStatusCode)
 {
        $description = "The server did not send back a well-formed response. " . PHP_EOL .
                       "Server Response: $body";
		throw new Errors\ServerError($description,ErrorCode::SERVER_ERROR,$httpStatusCode);	
  }
Error is it  Array to string conversion on above code. here we should check is array or string then be throw  Exception. we also define error code on **razorpay\razorpay\src\Errors\ServerError.php** 
because its take by default take order class as child class on file bellow file name 
2.**razorpay\razorpay\src\Entity.php**
 protected function getEntityUrl()
  {
        $fullClassName = get_class($this);
        $pos = strrpos($fullClassName, '\\');
        $className = substr($fullClassName, $pos + 1);
        $className = $this->snakeCase($className);
        return $className.'s/';
   }
  this function return **paymentLink** class of the child class.but here we pass **$api->paymentLink->all();**

### Actual behavior

$api = new Api($paymentGatewayKey,$paymentGatewaySecret);
$result=$api->paymentLink->all();

1.  **razorpay\razorpay\src\Request.php**
 protected function throwServerError($body, $httpStatusCode)
 {
        $description = "The server did not send back a well-formed response. " . PHP_EOL .
                       "Server Response: $body";
		throw new Errors\ServerError($description,ErrorCode::SERVER_ERROR,$httpStatusCode);	
  }
Error is it  Array to string conversion on above code.
because its take by default take order class as child class on file bellow file name 
2.**razorpay\razorpay\src\Entity.php**
 protected function getEntityUrl()
  {
        $fullClassName = get_class($this);
        $pos = strrpos($fullClassName, '\\');
        $className = substr($fullClassName, $pos + 1);
        $className = $this->snakeCase($className);
        return $className.'s/';
   }
  this function return **order** class of the child class.but here we pass **$api->paymentLink->all();**

### Code snippets

```Php
$api = new Api($paymentGatewayKey,$paymentGatewaySecret);
$result=$api->paymentLink->all();
```

### Php version

php 8.2

### Library version

razorpay-php v2.8.7

**Comment by ankitdas13** [comment]
@kirankumarmitnas Apologize for the delay.  Could you please let me know if this issue is resolved or not? 
Also how you were encountering this issue ? Were you integrating it into any framework ? 
Please explain the scenario

**Comment by kirankumarmitnas** [comment]
I am using CodeIgniter 4 PHP framework. i want to check all the payment received by using custom link.so i am using bellow code for get all the payment received by custom link.
$api = new Api($paymentGatewayKey,$paymentGatewaySecret);
$result=$api->paymentLink->all();
but whenever i am trying call paymentLink api .which is get error describe above comment. so i am trying to debug razorpay code. then i got some error clue which is error on initializing class of Entity class. file path of Entity class razorpay\razorpay\src\Entity.php. whenever i am calling $api->paymentLink->all(); is take by default class is "order" so it's call order api of the razorpay.

**Comment by kirankumarmitnas** [comment]
issue are solve.

**Comment by ankitdas13** [comment]
@kirankumarmitnas Thanks for the confirmation. Closing this issue
