### ISSUE TITLE
Resource is a reserved keyword in php 7

### ISSUE THREAD

**Issue by mayankamencherla** [razorpay/razorpay-php#37]
Resource has a soft reservation in php7 - which implies that the keyword is highly discouraged from being used as a class name. Our SDK, however, uses this keyword as a class name. 

http://php.net/manual/en/reserved.other-reserved-words.php#reserved.other-reserved-words

**Comment by ankitdas13** [comment]
the issue has been resolved in #330 
closing this ticket for now .
