### ISSUE TITLE
switch to composer/ca-bundle

### ISSUE THREAD

**Issue by captn3m0** [razorpay/razorpay-php#42]
https://github.com/composer/ca-bundle

We can use `CaBundle::getSystemCaRootBundlePath()` instead of the bundle we have committed (slightly outdated)

**Comment by ankitdas13** [comment]
Hi @captn3m0 do we still need this feature in PHP SDK?

**Comment by ankitdas13** [comment]
As per our discussion we will regularly add the updated `rmccue/requests`
