### ISSUE TITLE
Webhook validation error : invalid signature passed

### ISSUE THREAD

**Issue by phpnets** [razorpay/razorpay-php#48]
Hi,
In My test enviroment, I have used the following code to validate the Webhook:

```
try{
        	 if(!$oApi->utility->verifyWebhookSignature($requestBody, $razorPaySignature, $this->RAZOR_PAY_SECRET_KEY)) {
	            Log::info('Hash validation failed. so terminating the process');
	            die;
        	}
        }
        catch(Exception $e) {
        	Log::info('RazorPay Webhook validation Error: '.$e->getMessage());
        	die;
        }
```

Where $requestBody is the json encoded request data, $razorPaySignature is the value received form header X-Razorpay-Signature.
But always I'm getting this error : **Invalid signature passed**.
I'm sure the $this->RAZOR_PAY_SECRET_KEY contains right value.

This is the request JSON:

{
  "entity": "event",
  "event": "payment.authorized",
  "contains": [
    "payment"
  ],
  "payload": {
    "payment": {
      "entity": {
        "id": "pay_8Tikb77Pvn10yb",
        "entity": "payment",
        "amount": 1000,
        "currency": "INR",
        "status": "authorized",
        "order_id": null,
        "invoice_id": null,
        "international": false,
        "method": "netbanking",
        "amount_refunded": 0,
        "refund_status": null,
        "captured": false,
        "description": "Purchase Description",
        "card_id": null,
        "bank": "HDFC",
        "wallet": null,
        "vpa": null,
        "email": "support@razorpay.com",
        "contact": "123123456789",
        "notes": {
          "booking_id": "15666A",
          "service": "hotel"
        },
        "fee": null,
        "service_tax": null,
        "error_code": null,
        "error_description": null,
        "created_at": 1503320553,
        "tax": null
      }
    }
  },
  "created_at": 1503320554
}

**Comment by captn3m0** [comment]
Which package version are you currently at?

**Comment by phpnets** [comment]
@captn3m0 2.*

**Comment by captn3m0** [comment]
@phpnets Can you give us the output of `composer show|grep razorpay` to give us the exact version?

**Comment by phpnets** [comment]
@captn3m0 the version is 2.0.2

**Comment by captn3m0** [comment]
How are you reading the request JSON body?

**Comment by phpnets** [comment]
@captn3m0 
I used below both methods both return the same 
```
$requestBody 	   =  json_encode($oRequest->toArray());
OR
$requestBody 	   = $oRequest->getContent();
```
the $requestBody contains data I described in the question above

**Comment by captn3m0** [comment]
1. Looks like you are trying to verify the webhook signature using the Key Secret. You must use the webhook secret that you have specified while setting up the webhook
2. Please make sure you are getting the raw request body correctly. Our webhook requests do not contain newlines.

**Comment by phpnets** [comment]
@captn3m0 
 Yeah, the new key secret was not updated with webhook. Now It is okay.  And could you please clarify that the validation will not return true if it success right? So the try catch is enough to catch the unmatched hash?

    ```
try{
    	 $oApi->utility->verifyWebhookSignature($requestBody, $razorPaySignature, $this->RAZOR_PAY_SECRET_KEY) 
    }
    catch(Exception $e) {
    	Log::info('RazorPay Webhook validation Error: '.$e->getMessage());
    	die;
    }
```

Thank you.

**Comment by captn3m0** [comment]
Yes, we throw `Razorpay\Errors\SignatureVerificationError` in case the signature validation fails. The method will always return `null`
