### ISSUE TITLE
Does not return payment details in test account

### ISSUE THREAD

**Issue by naveen84123** [razorpay/razorpay-php#52]
I am trying to fetch payment details in my test account but can't get payment details 
 $api = new Api($this->razorpay_api_key, $this->razorpay_secret_key);
 $payment = $api->payment->fetch($request->payment_id);

this is returning empty  {} object.

**Comment by captn3m0** [comment]
Can you please send us the output of `var_dump($payment)` to integrations@razorpay.com please?
