### ISSUE TITLE
incorrect ID results in a unhandled exception

### ISSUE THREAD

**Issue by captn3m0** [razorpay/razorpay-php#60]
Instead of throwing a Razorpay\Exception (or a subclass), code throws ErrorException because of undefined index: Status.

Ref: 117901

**Comment by harman28** [comment]
Wasn't able to demonstrate this, is throwing `Razorpay\Api\Errors\BadRequestError` now, as expected. 

Closing, please reopen if needed, with code to recreate the issue.
