### ISSUE TITLE
Razorpay php server side integration without composer

### ISSUE THREAD

**Issue by android-bash** [razorpay/razorpay-php#66]
The documentation says i should download the razorpay-php.zip file. After that include Razorpay.php in your application. 
My project does not use composer.
I have all my php class files under sys->class folder. Example : sys->class->class.account.inc.php

Now i have extracted razorpay-php under sys folder. So folder structure looks like sys->razorpay-php

How do i use or include Razorpay.php in my class files? I am new to PHP and need help in setting up. Thank You.

**Comment by harishkotra** [comment]
@android-bash to include Razorpay.php, follow the steps below:

1. Copy Razorpay.php from the downloaded folder to your project folder
2. You can include it using include('Razorpay.php'); or require_once('Razorpay.php');

**Comment by captn3m0** [comment]
Thanks @harishkotra
