### ISSUE TITLE
order data returning null data

### ISSUE THREAD

**Issue by jayanthanantharapu** [razorpay/razorpay-php#69]
`use Razorpay\Api\Api;
$api = new Api($this->key, $this->secret);
$order_data = [<data>]
$api->order->create($order_data);`

On creating new order returning null data.
if i change the api keys getting invalid api key as exception from razor pay. but order is not creating.

**Comment by captn3m0** [comment]
Please make sure that you are using the right API Keys (generated from the Dashboard -> Settings). An order is successfully created if an exception is not raised.

If you still face an issue, please send us an email from your registered email address to <integrations@razorpay.com>. GitHub issues is for feature requests and bug reports in the SDK only.

**Comment by venkatasaikatepalli** [comment]
I have the same issue. I updated the Entity.php code as custom return object it working

**Comment by captn3m0** [comment]
@venkatasaikatepalli please send us an email at integrations@razorpay.com with sample code showing the issue.
