### ISSUE TITLE
naming a function on class name and use it as constructor has been deprecated from php

### ISSUE THREAD

**Issue by BlackXero** [razorpay/razorpay-php#71]
There are several classes function which are intended to work as constructor but now php don't support it. Please make an update to the SDK.
Thank You

**Comment by harman28** [comment]
Hi @BlackXero, sorry for the late response. I couldn't find examples of this in the current codebase (15th Sep 2018), so I'll be closing this issue. 

If this seems like a mistake, please feel free to open another issue and make note of the specific that classes you are referring to in the description.
