### ISSUE TITLE
Webhook not being fired for Route transfer

### ISSUE THREAD

**Issue by t-pankajkumar** [razorpay/razorpay-php#72]
When a transfer made to a linked account is settled the `settlement.processed` webhook is not fired.
Also, the scheduled transfer is not updating as settled even if the settlement date has crossed.

**Comment by harman28** [comment]
Hi @t-pankajkumar, sorry for the late response. I hope you were able to resolve your queries via the merchant support chat on your Razorpay dashboard, or via a mail sent to [support@razorpay.com](mailto:support@razorpay.com), which would be the more appropriate place for this question.

Closing this issue now as it is not related to the razorpay-php package.
