### ISSUE TITLE
'razorpay\Api\Api' not found in <b>/var/www/html/folder/api/index.php

### ISSUE THREAD

**Issue by pradeepan7899** [razorpay/razorpay-php#75]
After integration of php razorapi and deploying it in the server i'm getting above mentioned error message.
Eventhough **Api.php** file exist in the above mentioned folder .i.e. razorpay/Api/Api ..I'm getting as not found.?

![error](https://user-images.githubusercontent.com/34350536/40973826-3ab92e0c-68e3-11e8-99d0-0bf0632b96cc.png)

**Comment by kjhatis** [comment]
Using Codeigniter?
