### ISSUE TITLE
Subscription Cancel does not take parameters

### ISSUE THREAD

**Issue by deadmantfa** [razorpay/razorpay-php#82]
As per the documentation
https://razorpay.com/docs/subscriptions/api/#cancelling-a-subscription

I am allowed to send cancel_at_cycle_end parameter to cancel subscription API

But the code does not take any parameters for cancel
https://github.com/razorpay/razorpay-php/blob/master/src/Subscription.php

Function cancel

**Comment by deadmantfa** [comment]
I have made a pull request can you please review and accept the pull request so I can update our production servers

**Comment by harman28** [comment]
Solved in #83
