### ISSUE TITLE
Customer Creation Issue 

### ISSUE THREAD

**Issue by mansur-usis** [razorpay/razorpay-php#86]
Our customers are getting error if the try to pay using razor pay for the 2nd time using their same email address

![download_20180921_170624](https://user-images.githubusercontent.com/11188608/45913701-3f66cf00-be55-11e8-8727-7310aad9ce19.png)

**Comment by javaghost** [comment]
Ideal Response in case user search isn't available:
- Status code 200 with customer id in response when customer is present in razorpay customer database
- Status code 201 with customer id in response when customer is not present in razorpay database

Alternatively, provide search by email and phone to get the customer id. 

This case has become a bottleneck in my application and I've started exploring other payment gateways.

**Comment by harman28** [comment]
Use the `fail_existing` flag (documented [here](https://razorpay.com/docs/api/customers/#create-a-customer)) to retrieve the existing customer by contact.
