### ISSUE TITLE
razorpay recurring payments

### ISSUE THREAD

**Issue by dhananjayve** [razorpay/razorpay-php#88]
recurring payment options not available. Is any future plan to support recurring payment in this repo?

**Comment by PhilsonJohnPhilip** [comment]
Test comment for checking documentation notification

**Comment by PhilsonJohnPhilip** [comment]
Test comment for documentation purposes

**Comment by PhilsonJohnPhilip** [comment]
Testing again for comment notifications

**Comment by radhika-tk** [comment]
@dhananjayve : This feature is under development and will be available soon. Not yet released!

**Comment by harman28** [comment]
Support for subscriptions has been added.
