### ISSUE TITLE
The requested URL was not found on the server.

### ISSUE THREAD

**Issue by malsubrata** [razorpay/razorpay-php#93]
When I try to create a new transfer request it says "The requested URL was not found on the server"

my request was 

`$transfer = $api->transfer->create(array('account' => 'Customer Id', 'amount' => 10, 'currency' => 'INR'));`

Please help me to fix this.

**Comment by Mayur-Wadpalliwar** [comment]
@malsubrata Please login to your Razorpay dashboard, and submit the product submission form for Route
