### ISSUE TITLE
QR Code Auto Redirect Handler method in razorpay

### ISSUE THREAD

**Issue by viveksingh111** [razorpay/razorpay-php#94]
When i use razorpay and choose QR Scanner to payment then without taking any payment in comes in handler method with payment id and signature.

Please check this.
Reply as soon as possible

Regards,
Vivek

**Comment by pronav** [comment]
Hi Vivek, this is the behavior for test mode, QR will wait for actual payment to happen with live keys.

**Comment by Shyam-Raghuwanshi** [comment]
hi @viveksingh111 facing same issue the QR scanner handler not detecting the payment on deployed website but it's working locally
and I have the live keys not the test
