### ISSUE TITLE
Currency is not supported error

### ISSUE THREAD

**Issue by akadebnath** [razorpay/razorpay-php#95]
As per [this ](https://docs.razorpay.com/page/multi-currency-payments) doc, when creating an order, we can simply pass the currency parameter in Order as USD or EUR.

However, in practice, I am not able to make it to work.

It only works when currency parameter is 'INR'.

My code:

```
<?php
require 'vendor/autoload.php';
use Razorpay\Api\Api;
$api = new Api('rzp_test_xxxxxxxxxxxxxxxxxx', 'xxxxxxxxxxxxxxxxxxxxx');
$order  = $api->order->create(array('receipt' => '123', 'amount' => 100, 'currency' => 'USD'));
?>
```

On running this code, I am getting this error:

> Fatal error: Uncaught Razorpay\Api\Errors\BadRequestError: Currency is not supported in D:\Freelancer\skipqlah\vendor\razorpay\razorpay\src\Request.php:120 Stack trace: #0 D:\Freelancer\skipqlah\vendor\razorpay\razorpay\src\Request.php(90): Razorpay\Api\Request->processError(Array, 400, Object(Requests_Response)) #1 D:\Freelancer\skipqlah\vendor\razorpay\razorpay\src\Request.php(44): Razorpay\Api\Request->checkErrors(Object(Requests_Response)) #2 D:\Freelancer\skipqlah\vendor\razorpay\razorpay\src\Entity.php(79): Razorpay\Api\Request->request('POST', 'https://api.raz...', Array) #3 D:\Freelancer\skipqlah\vendor\razorpay\razorpay\src\Entity.php(15): Razorpay\Api\Entity->request('POST', 'orders/', Array) #4 D:\Freelancer\skipqlah\vendor\razorpay\razorpay\src\Order.php(12): Razorpay\Api\Entity->create(Array) #5 D:\Freelancer\skipqlah\rzp_order.php(15): Razorpay\Api\Order->create(Array) #6 {main} thrown in D:\Freelancer\skipqlah\vendor\razorpay\razorpay\src\Request.php on line 120

**Comment by radhika-tk** [comment]
Hello,

1. Please refer this FAQ in Razorpay's KB site: https://razorpay.com/knowledgebase/
2. Please write to  you get the multicurrency feature enabled on your account, in the first place. 

Hope this helps.

Thanks,
Radhika

**Comment by chakri741** [comment]
same error bro have you done it ??

**Comment by akadebnath** [comment]
There are something in the documentation, however, we ended up using INR only as the business in only for India.
