### ISSUE TITLE
Exception - Class 'Requests_Hooks' not found

### ISSUE THREAD

**Issue by spinozarabel** [razorpay/razorpay-php#97]
I am getting the php error, 
_Exception - Class '**Requests_Hooks**' not found_
on line 44 of entity.php, here is the code snippet below and the stack trace below it.
(I am using your php library, and had to comment out lines 4-21 of Razorpay.php since it was calling Requests.php from a non-existant /libs directory in your library. )
-----------------------------------------------------------------------------------------------------
require_once(__DIR__ . '/razorpay-php-master/Razorpay.php');
//    use Razorpay\Api\Api;

    $api_key    = "my key here";
    $api_secret = "my secret here";

$api = new Razorpay\Api\Api($api_key, $api_secret);

        $va_constructor = array(
							'receivers' => array('types' => array('bank_account')), 
							'description' 	 => 'Virtual Account for Sritoni1 Moodle1', 
							'notes' 		 => array(
														'sritoni_id' => '00_00-01'
													 )
							);
        $virtualAccount  = $api->virtualAccount->create($va_constructor);
---------------------------stack trace below-------------------------------------------------

- line 44 of /blocks/configurable_reports/export/wpsync/razorpay-php-master/src/Request.php: Error thrown
- line 79 of /blocks/configurable_reports/export/wpsync/razorpay-php-master/src/Entity.php: call to Razorpay\Api\Request->request()
- line 15 of /blocks/configurable_reports/export/wpsync/razorpay-php-master/src/Entity.php: call to Razorpay\Api\Entity->request()
- line 9 of /blocks/configurable_reports/export/wpsync/razorpay-php-master/src/VirtualAccount.php: call to Razorpay\Api\Entity->create()
- line 46 of /blocks/configurable_reports/export/wpsync/export.php: call to Razorpay\Api\VirtualAccount->create()
- line 117 of /blocks/configurable_reports/viewreport.php: call to export_report()

**Comment by captn3m0** [comment]
Looks like you downloaded the wrong file. From the README:

>If you are not using composer, download the latest release from the releases section. You should download the razorpay-php.zip file. After that include Razorpay.php in your application and you can use the API as usual.

Please download the `razorpay-php.zip` file: https://github.com/razorpay/razorpay-php/releases/tag/2.4.0-beta

**Comment by vimalgang** [comment]
How to create plan for every customers ?

**Comment by captn3m0** [comment]
Please create a new issue, or reach out to our support team using https://razorpay.com/support
