### ISSUE TITLE
Golang SDK for Razorpay?

### ISSUE THREAD

**Issue by rebootcode** [razorpay/razorpay-php#98]
Hi,

Since there is no option to create an issue in razorpay for new SDK, I am requesting here. Please provide me correct place to post this?

Does razorpay have official Golang SDK?

**Comment by captn3m0** [comment]
Hi,

The Razorpay golang SDK is currently in private beta. I'll send you an invite over GitHub.

**Comment by rebootcode** [comment]
@captn3m0 - Thanks waiting for it!
